// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hello.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ASY.Hrefs.gRPC.Interface {
  public static partial class HelloSrv
  {
    static readonly string __ServiceName = "hello.HelloSrv";

    static readonly grpc::Marshaller<global::ASY.Hrefs.gRPC.Interface.HelloRequest> __Marshaller_hello_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ASY.Hrefs.gRPC.Interface.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ASY.Hrefs.gRPC.Interface.HelloReply> __Marshaller_hello_HelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ASY.Hrefs.gRPC.Interface.HelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::ASY.Hrefs.gRPC.Interface.HelloRequest, global::ASY.Hrefs.gRPC.Interface.HelloReply> __Method_SayHello = new grpc::Method<global::ASY.Hrefs.gRPC.Interface.HelloRequest, global::ASY.Hrefs.gRPC.Interface.HelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_hello_HelloRequest,
        __Marshaller_hello_HelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ASY.Hrefs.gRPC.Interface.HelloReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HelloSrv</summary>
    [grpc::BindServiceMethod(typeof(HelloSrv), "BindService")]
    public abstract partial class HelloSrvBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::ASY.Hrefs.gRPC.Interface.HelloReply> SayHello(global::ASY.Hrefs.gRPC.Interface.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HelloSrv</summary>
    public partial class HelloSrvClient : grpc::ClientBase<HelloSrvClient>
    {
      /// <summary>Creates a new client for HelloSrv</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HelloSrvClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HelloSrv that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HelloSrvClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HelloSrvClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HelloSrvClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::ASY.Hrefs.gRPC.Interface.HelloReply SayHello(global::ASY.Hrefs.gRPC.Interface.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::ASY.Hrefs.gRPC.Interface.HelloReply SayHello(global::ASY.Hrefs.gRPC.Interface.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::ASY.Hrefs.gRPC.Interface.HelloReply> SayHelloAsync(global::ASY.Hrefs.gRPC.Interface.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::ASY.Hrefs.gRPC.Interface.HelloReply> SayHelloAsync(global::ASY.Hrefs.gRPC.Interface.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HelloSrvClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HelloSrvClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HelloSrvBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, HelloSrvBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SayHello, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ASY.Hrefs.gRPC.Interface.HelloRequest, global::ASY.Hrefs.gRPC.Interface.HelloReply>(serviceImpl.SayHello));
    }

  }
}
#endregion
